# Generated by Django 2.2.9 on 2020-01-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='add/')),
                ('image2', models.ImageField(upload_to='add/')),
                ('image3', models.ImageField(upload_to='add/')),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('text4', models.CharField(max_length=100)),
            ],
        ),
    ]
