# Generated by Django 2.2.9 on 2020-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abouthero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
            ],
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
