# Generated by Django 2.2.9 on 2020-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20200123_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipe/')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
