# Generated by Django 2.2.9 on 2020-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_recipessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipegallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='gallery/')),
                ('image2', models.ImageField(upload_to='gallery/')),
                ('image3', models.ImageField(upload_to='gallery/')),
                ('image4', models.ImageField(upload_to='gallery/')),
                ('image5', models.ImageField(upload_to='gallery/')),
                ('image6', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
