# Generated by Django 2.2.9 on 2020-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.ImageField(upload_to='footer/')),
                ('image1', models.ImageField(upload_to='gallery/')),
                ('date', models.DateField(auto_now=True)),
                ('title2', models.ImageField(upload_to='footer/')),
                ('rating', models.IntegerField()),
                ('image2', models.ImageField(upload_to='gallery/')),
                ('title3', models.ImageField(upload_to='footer/')),
                ('author', models.CharField(max_length=100)),
                ('description', models.ImageField(upload_to='footer/')),
            ],
        ),
    ]
