# Generated by Django 2.2.9 on 2020-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='title1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title3',
            field=models.CharField(max_length=100),
        ),
    ]
