# Generated by Django 2.2.9 on 2020-01-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20200123_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='title3',
        ),
    ]
