# Generated by Django 2.2.9 on 2020-01-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_auto_20200123_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='image2',
        ),
    ]
