# Generated by Django 2.2.9 on 2020-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_remove_footer_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='agallery/')),
                ('image2', models.ImageField(upload_to='agallery/')),
                ('image3', models.ImageField(upload_to='agallery/')),
                ('image4', models.ImageField(upload_to='agallery/')),
                ('image5', models.ImageField(upload_to='agallery/')),
                ('image6', models.ImageField(upload_to='agallery/')),
            ],
        ),
    ]
