# Generated by Django 2.2.9 on 2020-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_auto_20200127_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agallery',
            name='image1',
            field=models.ImageField(upload_to='agallery/'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='image1',
            field=models.ImageField(upload_to='fact/'),
        ),
    ]
