# Generated by Django 2.2.9 on 2020-01-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_auto_20200127_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='title',
        ),
    ]
