# Generated by Django 2.2.9 on 2020-01-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_write'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
